routes/web.php
<?php

/*
Home Routes
*/ 

Route::get('/', function () {
    return view('cliente.inicio');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::get("inicio", 'HomeController@inicio')->name('home.inicio');

Route::get("show/{id}", 'HomeController@show')->name('home.show');

Route::get("createConsulta/{id}", 'HomeController@createConsulta')->name('home.createConsulta');

Route::post("saveConsulta/{id}", 'HomeController@saveConsulta')->name('home.saveConsulta');

Route::get("pesquisa", 'HomeController@pesquisa')->name('home.pesquisa');


/*
Doutors Routes
*/
Route::resource('doutores', 'DoutorController')->middleware('auth');

Route::get("createSetor", 'DoutorController@createSetor')->name('doutores.createSetor');

Route::post("saveSetor", 'DoutorController@saveSetor')->name('doutores.saveSetor');

Route::get("viewConsultas", 'DoutorController@viewConsultas')->name('doutores.viewConsultas');

Route::get("consultaDoutor", 'DoutorController@consultaDoutor')->name('doutores.consultaDoutor');

Route::get("relatorio", 'DoutorController@relatorio')->name('doutores.relatorio');

/*E-mail*/ 
Route::post('/send', 'EmailController@send')->name('email.send');


Auth::routes();

resources/views/admin/consultaDoutor.blade.php
@extends('admin.modelo') 
@section('conteudo')

<div class="row">
  <div class="col-sm-10">
     <h3>Consultas Marcadas</h3>
  </div>   
</div>

@if (session('status'))
<div class="alert alert-success">
  {{ session('status') }}
</div>
@endif


<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
 google.charts.load("current", {packages:["corechart"]});
 google.charts.setOnLoadCallback(drawChart);

 function drawChart() {
    var data = google.visualization.arrayToDataTable([['Doutor', 'Saldo']
    @foreach ($linhas as $linha)
      {!! ",['$linha->nome', $linha->saldo]" !!}
    @endforeach
    ]);
    var options = {
      title: 'Percentual do Saldo de cada Doutor em relação ao lucro gerado pelo hospital',
      is3D: true,
    };
    var chart = new google.visualization
    .PieChart(document.getElementById('piechart_3d'));
    chart.draw(data, options);
 }
</script>
<div id="piechart_3d" style="width: 900px; height: 500px;"></div>

<table class="table table-hover">
  <thead>
    <tr>
    <th>Saldo</th>
      <th>Nome do Doutor</th>
      <th>Setor</th>
      <th>Total de Pacientes</th>
    </tr>
  </thead>
  <tbody>

    @foreach ($linhas as $linha)
    <tr>
      <td> R$ {{ $linha->saldo }} </td> 
      <td> {{ $linha->nome }} </td> 
      <td> {{ $linha->setor->setor }} </td>
      <td> {{ $linha->qtd }} </td> 
  </tr>

    @endforeach

  </tbody>
</table>


@endsection

resources/views/admin/form_doutores.blade.php
@extends('admin.modelo') 

@section('conteudo')
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif 

@if ($acao == 1)
  <h3>Inclusão de doutores</h3>
  <form method="post" action="{{ route('doutores.store') }}" enctype="multipart/form-data">

@elseif ($acao == 2)
  <h3>Alteração de doutores</h3>
  <form method="post" action="{{ route('doutores.update', $reg->id) }}" enctype="multipart/form-data">
  {{ method_field('put') }} 
    

@endif 

{{ csrf_field() }}

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label for="nome">Nome do Doutor:</label>
            <input type="text" class="form-control" id="nome" name="nome" 
                  value="{{$reg->nome or old('nome')}}" autofocus> 
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <label for="setor_id">Setor</label>
          <select id="setor_id" name="setor_id" class="form-control">
            @foreach($setors as $m)
              <option value="{{$m->id}}" 
                      {{ ((isset($reg) and $reg->setor_id == $m->id) or 
                         old('setor_id') == $m->id) ? "selected" : "" }}>
                      {{$m->setor}}</option>
            @endforeach
          </select>  
        </div>
      </div>
    </div>

          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <label for="cpf">Cpf:</label>
                <input type="text" class="form-control" id="cpf" name="cpf"
                      value="{{$reg->cpf or old('cpf')}}"> 
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <label for="sala">Sala:</label>
                <input type="text" class="form-control" id="sala" name="sala"
                      value="{{$reg->sala or old('sala')}}"> 
              </div>
            </div>
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <label for="precoConsulta">Preço da Consulta:</label>
                <input type="text" class="form-control" id="precoConsulta" name="precoConsulta"
                      value="{{$reg->precoConsulta or old('precoConsulta')}}"> 
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <label for="email">E-mail:</label>
                <input type="text" class="form-control" id="email" name="email"
                      value="{{$reg->email or old('email')}}" >
              </div>
            </div>
          </div>

            <div class="col-sm-6">
              <div class="form-group">
                <label for="foto">Foto:</label>
                <input type="file" class="form-control" id="foto" name="foto">
              </div>
            </div>
          </div>

          <input type="submit" value="Enviar" class="btn btn-danger">
        </form>
      </div>
    </div>

@endsection

resources/views/admin/form_setores.blade.php
@extends('admin.modelo') 

@section('conteudo')
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif 

  <h3>Inclusão de Setor</h3>
  <form method="post" action="{{ route('doutores.saveSetor') }}">

    {{ csrf_field() }}
    <div class="row">
      <div class="col-sm-4">
        <div class="form-group">
          <label for="setor_id">Setores já cadastrados</label>
          <select id="setor_id" name="setor_id" class="form-control" readonly="readonly">
            @foreach($setors as $m)
              <option value="{{$m->id}}" 
                      {{ ((isset($reg) and $reg->setor_id == $m->id) or 
                         old('setor_id') == $m->id) ? "selected" : "" }}>
                      {{$m->setor}}</option>
            @endforeach
          </select>  
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label for="setor">Nome do Setor:</label>
            <input type="text" class="form-control" id="setor" name="setor" 
                  value="{{$reg->setor or old('setor')}}" autofocus> 
        </div>
      </div>
    </div>
    
    <input type="submit" value="Enviar" class="btn btn-danger">
  </form>

@endsection

resources/views/admin/lista_doutores.blade.php
@extends('admin.modelo') 
@section('conteudo')

<div class="row">
  <div class="col-sm-10">
     <h3>Doutores Disponiveis</h3>
  </div>   
  <div class="col-sm-2">
    <a href="{{ route('doutores.create') }}" class="btn btn-primary btn-sm" style="margin-top:24px" role="button">Incluir</a>
  </div>   
</div>

@if (session('status'))
<div class="alert alert-success">
  {{ session('status') }}
</div>
@endif

<table class="table table-hover">
  <thead>
    <tr>
    <th>Cód.</th>
      <th>Nome do Doutor</th>
      <th>Area</th>
      <th>Preço da Consulta</th>
      <th>E-mail</th>
      <th>Foto</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>

    @foreach ($linhas as $linha)
    <tr>
      <td> {{ $linha->id }} </td> 
      <td> {{ $linha->nome }} </td> 
      <td> {{ $linha->setor->setor }} </td>
      <td> R$ {{ $linha->precoConsulta }} </td> 
      <td> {{ $linha->email }} </td>
      <td> <img src='storage/{{ $linha->foto }}' style='width: 120px; height: 80px;'> </td>
      <td> <a href="{{ route('doutores.edit', $linha->id) }}" class="btn btn-info btn-sm" role="button">Alterar</a>&nbsp; 
          <a href="{{ route('doutores.show', $linha->id) }}" class="btn btn-success btn-sm" role="button">Consultar</a>&nbsp; 
          <form method="post" action="{{ route('doutores.destroy', $linha->id)}}"
                style="display: inline-block"
                onsubmit="return confirm('Confirma Exclusão deste Doutor?')">               
            {{ csrf_field() }}
            {{ method_field('delete') }}
            <input type="submit" class="btn btn-danger btn-sm" 
                  value="Excluir">
          </form>                   
        </td>
  </tr>

    @endforeach

  </tbody>
</table>
@endsection

resources/views/admin/modelo.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>Hospital</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{{ route('home.inicio') }}">Hospital</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{{ route('doutores.index') }}">Home</a></li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Cadastros <span class="caret"></span></a>
        <ul class="dropdown-menu">
        <li><a href="{{ route('doutores.create') }}">Doutor</a></li>
        <li><a href="{{ route('doutores.createSetor') }}">Setor</a></li>
        </ul>
      </li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Consultas<span class="caret"></span></a>
        <ul class="dropdown-menu">
        <li><a href="{{ route('doutores.viewConsultas') }}">Todas</a></li>
        <li><a href="{{ route('doutores.consultaDoutor') }}">Por Setor</a></li>
        </ul>
      </li>
      <li><a href="{{ route('doutores.relatorio') }}">Gerar PDF</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    <li><a href="{{ route('login') }}"><span class="glyphicon glyphicon-user"></span> {{ Auth::user()->name }}</a></li>
      <li>
          <a href="{{ route('logout') }}"
          onclick="event.preventDefault();
                   document.getElementById('logout-form').submit();"><span class="glyphicon glyphicon-log-in"></span>
          Sair
      </a>

      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
          {{ csrf_field() }}
      </form>        
      </li>
    </ul>
  </div>
</nav>
  
<div class="container">

@yield('conteudo')  

</div>

</body>
</html>

resources/views/admin/relatorio.blade.php
<div class="container-fluid">
    <h4 style="text-align: center">Revenda Herbie</h4>
    <h5 style="text-align: center">Relatório de Veículos Cadastrados</h5>
    <table class="table table-bordered table-sm">
        <thead class="thead-light">
            <tr>
                <th>Nome</th>
                <th>Setor</th>
                <th>E-mail</th>
                <th>Total de Pacientes</th>
                <th>Saldo Total</th>
                <th>Foto</th>
            </tr>
            </thead>
        <tbody>
            @foreach($linhas as $linha)
                <tr>
                    <td>{{$linha->nome}}</td>
                    <td>{{$linha->setor->setor}}</td>
                    <td>{{$linha->email}}</td>
                    <td>{{$linha->qtd}}</td>
                    <td>R$ {{$linha->saldo}}</td>
                    @if (Storage::exists($c->foto))
                        <img src="{{public_path('storage/'.$linha->foto)}}" style="width:100px;height:60px">
                    @else
                        <img src="{{public_path('storage/fotos/semfoto.png')}}">
                    @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
        </table>
</div>

resources/views/admin/view_consultas.blade.php
@extends('admin.modelo') 
@section('conteudo')

<div class="row">
  <div class="col-sm-10">
     <h3>Consultas Marcadas</h3>
  </div>   
</div>

@if (session('status'))
<div class="alert alert-success">
  {{ session('status') }}
</div>
@endif

<table class="table table-hover">
  <thead>
    <tr>
    <th>Data</th>
      <th>Nome do Paciente</th>
      <th>E-mail</th>
      <th>Preço da Consulta</th>
      <th>Doutor</th>
      <th>Setor</th>
      <th>Lembrete</th>
    </tr>
  </thead>
  <tbody>

    @foreach ($linhas as $linha)
    <tr>
      <td> {{ $linha->data }} </td> 
      <td> {{ $linha->nome }} </td> 
      <td> {{ $linha->email }} </td>
      <td> R$ {{ $linha->doutor->precoConsulta }} </td> 
      <td> {{ $linha->doutor->nome }} </td>
      <td> {{ $linha->doutor->setor->setor }} </td>
      <td> <a href="{{ route('email.send')}}" class="btn btn-danger btn-sm" role="button">Enviar Lembrete</a></td>
  </tr>

    @endforeach

  </tbody>
</table>
@endsection

resources/views/admin/view_doutor.blade.php
@extends('admin.modelo') 

@section('conteudo')
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif 

    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    </head>
    <body>
        <h2 value="{{$reg->nome or old('nome')}}"></h2>
        <div class="card img-fluid" style="width:500px">
            <img class="card-img-top" src="storage/{{ $reg->foto }}" alt="Card image" style="width:100%">
            <div class="card-img-overlay">
                CPF: <input type="text" class="form-control" id="cpf" name="cpf" value="{{$reg->cpf or old('cpf')}}" readonly="readonly">
                Sala: <input type="text" class="form-control" id="sala" name="sala" value="{{$reg->sala or old('sala')}}" readonly="readonly">
                Preço da Consulta: <input type="text" class="form-control" id="precoConsulta" name="precoConsulta" value="{{$reg->precoConsulta or old('precoConsulta')}}" readonly="readonly">
                E-mail: <input type="text" class="form-control" id="email" name="email" value="{{$reg->email or old('email')}}" readonly="readonly">
                Setor: <input type="text" class="form-control" id="setor_id" name="setor_id" value="{{$reg->setor->setor}}" readonly="readonly">
                <br/>
                <a href="{{ route('doutores.edit', $reg->id) }}" class="btn btn-primary">Alterar dados</a>
            </div>
        </div>
    </body>

@endsection